### ISSUE TITLE
Client using deprecated 1.2 version of js library

### ISSUE THREAD

**Issue by jhurdlow** [TwilioDevEd/browser-calls-csharp#16]
This sample is still using the now deprecated 1.2 version of the twilio.js library. Should be updated to use current 1.4 version.

**Comment by itsunu** [comment]
https://github.com/twilio/OpenVBX/issues/427

I am rebuilded Openvbx system using latest twilio libraries ,APis and also latest Codeignite verison,
please contact me for updated OpenVBX
mail :- husainnki@gmail.com
SKYPE : muhammedhusaintk
mobile : +919562470582

Twilio Client 1.2 is deprecated today feb 14, 2018

Warning: Twilio Client 1.2 is deprecated and will reach end of life on February 14, 2018. On this date, Twilio will stop serving this file through the CDN and will begin refusing connections used by this library. We recommend updating to 1.4 as soon as possible. See the full documentation at https://www.twilio.com/docs/api/client/twilio-js-14 for more information.
