### ISSUE TITLE
Exception in js script and calls not working

### ISSUE THREAD

**Issue by YoussefWaelMohamedLotfy** [TwilioDevEd/browser-calls-csharp#246]
The "Connecting to twilio..." never changes. I followed every step in the readme.md and this exception shows when i click on Call Customer button. What may I have missed?

![image](https://user-images.githubusercontent.com/40206862/106523328-9ed74e00-64e9-11eb-84f2-5fe9b26abfc1.png)

**Comment by davidlfox** [comment]
not a solution, but i just ran this locally, and it doesnt look like its properly bundling jquery scripts. might be something there...investigating

**Comment by davidlfox** [comment]
hack fix--go into /Views/_Layout.cshtml and replace:

```
@Scripts.Render("~/bundles/scripts")
```

with:

```
@Scripts.Render("~/Scripts/jquery-3.4.1.js")
@Scripts.Render("~/Scripts/browser-calls.js")
```

**Comment by YoussefWaelMohamedLotfy** [comment]
@davidlfox This actually solved the problem. Much appreciated.
