### ISSUE TITLE
Mitigate need to use View path in Tickets controller

### ISSUE THREAD

**Issue by devinrader** [TwilioDevEd/browser-calls-csharp#4]
Using the string path to the Home view form the Tickets controller is pretty brittle.

https://github.com/TwilioDevEd/browser-calls-csharp/blob/master/BrowserCalls.Web/Controllers/TicketsController.cs#L30

I can see two options here that might be better:

- Move the Index view currently loaded by the HomeController to the Tickets controller and change the default route
- Move the Index view currently loaded by the HomeController to the Tickets controller and use Attribute routing to apply both ad default and a specific route to it

**Comment by acamino** [comment]
I see, actually it is more evident when you think in something like using a `ViewBag`, with the current approach this is not possible.

I like the first approach you proposed, it feels more natural to me. I'll be opening a PR soon.
