### ISSUE TITLE
Is TempData the right storage?

### ISSUE THREAD

**Issue by devinrader** [TwilioDevEd/browser-calls-csharp#5]
Are you sure you want to use TempData here vs ViewBag?

https://github.com/TwilioDevEd/browser-calls-csharp/blob/master/BrowserCalls.Web/Views/Shared/_Messages.cshtml#L1

IIRC TempData will persist in session across multiple requests, so if I reading your code right, if I go away from and then come back to this page the message will continue to show.

I think ViewBag only persists for the single HTTP request.

**Comment by acamino** [comment]
You right @devinrader, looks like `TempData` is not what we should be using here, I need to do some changes in order to use `ViewBag`, thanks for pointing me out in the right direction.
