### ISSUE TITLE
Should Twilio Client be included on every page in the site?

### ISSUE THREAD

**Issue by devinrader** [TwilioDevEd/browser-calls-csharp#6]
Right now the Twilio Client JS is included in every page of the site.  Is that intended?

https://github.com/TwilioDevEd/browser-calls-csharp/blob/master/BrowserCalls.Web/Views/Shared/_Layout.cshtml#L36

If not consider using a scripts section to inject this script into only the pages that need it.

**Comment by atbaker** [comment]
I can chime in on this one. The Browser Calls sample app only has two pages - a "File a support ticket" page and a "Support Agent dashboard" page.

We have a client widget on each, so including the Client JS on every page of the app isn't a huge deal to me, but I'll defer to your judgment as to how a C# dev would feel about it.

**Comment by devinrader** [comment]
If its on every page then loading it in the shared template is cool.

**Comment by acamino** [comment]
Thank you guys!
