### ISSUE TITLE
Key Attribute on Tickets model

### ISSUE THREAD

**Issue by devinrader** [TwilioDevEd/browser-calls-csharp#8]
Does this need a Key attribute applied:

https://github.com/TwilioDevEd/browser-calls-csharp/blob/master/BrowserCalls.Web/Models/Ticket.cs#L8

**Comment by acamino** [comment]
Key attribute is not mandatory when you're defining a model, `Key` attribute is optional in this case. Whenever you define an `Id` attribute, then _EF_ is smart enough to use that field as the primary key.

**Comment by devinrader** [comment]
Ah, right.  I never just use `Id` as the key property name, but its legit to do that.
